### ISSUE TITLE
Clearflask connect has hardcoded values

### ISSUE THREAD

**Issue by Supernova3339** [clearflask/clearflask#110]
Hi, our team doesn't like that the values are hardcoded, and as such makes it impossible to deploy on our infastructure. Would you happen to have a way or solution to solve this problem?

Any help is appreciated. Thanks in advance.

**Comment by matusfaro** [comment]
Hi @Supernova3339, what particular values are hardcoded that you would like to change?

**Comment by Supernova3339** [comment]
for the clearflask-viewer the URL to connect to the backend is hardcoded.
This is bad practice. If you would like, I can craft a PR to fix this issue.

**Comment by matusfaro** [comment]
By `clearflask-viewer` I assume you mean `clearflask-connect`? There is a configuration parameter to specify the backend API endpoint here: https://github.com/clearflask/clearflask/blob/master/clearflask-frontend/src/connect/config.ts#L28
Please let me know if you mean something else.

**Comment by Supernova3339** [comment]
> https://github.com/clearflask/clearflask/blob/master/clearflask-frontend/src/connect/config.ts#L28

Is there an ENV? I tried to deploy it from docker-compose

**Comment by Supernova3339** [comment]
One more thing, is it possible to specify S3 connection details from ENV?

**Comment by matusfaro** [comment]
> Is there an ENV? I tried to deploy it from docker-compose

When you deploy using docker-compose, the configuration files will be auto-created in the same folder. You can modify these properties.

> is it possible to specify S3 connection details from ENV?

Not from an environment variable, but using the configuration file for clearflask-server you can change this property:
https://github.com/clearflask/clearflask/blob/master/clearflask-server/src/main/resources/config-selfhost.cfg#L89

**Comment by Supernova3339** [comment]
I did notice that parts of the S3 can be defined from variables, albeit
confusing. If I created a PR ( will take a few weeks ) to provide ENV
configuration alongside the config file, would this work as a proper
solution?
I can also look into that github integration you specified, as it seems
certain values are hardcoded and changes are recommended to ensure proper
connectivity.

**Comment by matusfaro** [comment]
> github integration you specified, as it seems certain values are hardcoded

Have you tried following the configuration guide to set it up? https://github.com/clearflask/clearflask/blob/master/clearflask-server/src/main/resources/config-selfhost.cfg#L108

If there are hardcoded config files I can fix it for you. Just let me know what's not working. The code for the Github integration is here: https://github.com/clearflask/clearflask/blob/master/clearflask-server/src/main/java/com/smotana/clearflask/store/github/GitHubStoreImpl.java#L115

> to provide ENV configuration alongside the config file

For Java/`clearflask-server` side: you would need to create a class `EnvironmentDynamicConfigSource` that extends the `AbstractDynamicConfigSource` to add a source for configuration via environment variables. You can read more about the config library here: https://github.com/kikinteractive/ice

For NodeJS/`clearflask-connect` side: you should add changes to the `config.ts` file to pull config overrides from environment variables.
