### ISSUE TITLE
Image upload results in broken picture

### ISSUE THREAD

**Issue by fhsevenbel** [clearflask/clearflask#113]
Our team has a self hosted clearflask instance behind an nginx proxy server.
It is working fine but every time we want to upload an image the only thing being shown is this:
![image](https://user-images.githubusercontent.com/66937832/232810717-4434e59b-b107-4ef6-8696-1fa6a82d8663.png)

---

According to our Nginx logs the upload resulted in an HTTP 200
```
SOME_VALID_IP - - [18/Apr/2023:14:35:25 +0000] "POST /api/v1/project/OUR_PROJECT_ID/content/upload HTTP/2.0" 200 313 "https://clearflask.VALID_DOMAIN_NAME.dev/dashboard/feedback" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
SOME_VALID_IP - - [18/Apr/2023:14:35:26 +0000] "POST /api/v1/project/OUR_PROJECT_ID/content/upload HTTP/2.0" 200 312 "https://clearflask.VALID_DOMAIN_NAME.dev/dashboard/feedback" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
SOME_VALID_IP - - [18/Apr/2023:14:35:26 +0000] "POST /api/v1/project/OUR_PROJECT_ID/content/upload HTTP/2.0" 200 313 "https://clearflask.VALID_DOMAIN_NAME.dev/dashboard/feedback" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
SOME_VALID_IP - - [18/Apr/2023:14:35:26 +0000] "POST /api/v1/project/OUR_PROJECT_ID/content/upload HTTP/2.0" 200 315 "https://clearflask.VALID_DOMAIN_NAME.dev/dashboard/feedback" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
SOME_VALID_IP - - [18/Apr/2023:14:35:26 +0000] "POST /api/v1/project/OUR_PROJECT_ID/content/upload HTTP/2.0" 200 312 "https://clearflask.VALID_DOMAIN_NAME.dev/dashboard/feedback" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
```

We already tried our best to disable all restrictions for the nginx instance with no luck, i mean the 200 code did not change, but pictures are still broken.

---

Also while filtering through our clearflask logs we did not find any suspicious things at first glance:
(our IP's and company name were removed)
[logs.txt](https://github.com/clearflask/clearflask/files/11263068/logs.txt)

---

The docker-compose we are using is this one:
(as txt file because github does not support .yml files in messages it seems)
(ENV variables are set and working!)
[docker-compose.yml.txt](https://github.com/clearflask/clearflask/files/11263077/docker-compose.yml.txt)

--- 

Any help or advice would be appreciated as we cannot really find similar problems on the internet.

**Comment by fhsevenbel** [comment]
As i did not set up our clearflask i am not a 100% sure where to find the source URL, can i find it in the logs or is it configurable?

**Comment by matusfaro** [comment]
Right click on the broken image and open the image in new window and note down the URL

**Comment by fhsevenbel** [comment]
Thanks 😅 

Here is the URL:
```
https://local-upload.s3.localhost.localstack.cloud:4566/img/ugc/clearflask-qhoy/fabian-hintringer-cv5/f8591b96650848ccb121eee51ae73428.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230418T144011Z&X-Amz-SignedHeaders=host&X-Amz-Expires=10800&X-Amz-Credential=test%2F20230418%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=268ec24a73f341927dd7fffd355ea4e41e2506e5f70708b99fccd80a76f2f73f
```

**Comment by matusfaro** [comment]
Thanks that clears it up. Actually this is a bug on our side with self-hosted option.

Localstack was never intended to be used in production, but since I made it part of the quick deploy I need to support it. Let me think about how to go about fixing this and I'll get back to you.

**Comment by matusfaro** [comment]
The fix is on the way, watch out for the next release 1.6.4 shortly

You will need to add these two properties with the release 1.6.4:
```
com.smotana.clearflask.store.impl.S3ContentStore$Config.proxyEnabled=true
com.smotana.clearflask.store.impl.S3ContentStore$Config.proxyResolveTo=localstack
```
