### ISSUE TITLE
Announcements must be saved as a draft before they can be published

### ISSUE THREAD

**Issue by julianebert** [clearflask/clearflask#119]
I use the cloud version of ClearFlask. As soon as I try to publish a newly created announcement via the primary "Submit" button, nothing happens. You have to save the article as a draft beforehand. After that, the primary button works as expected. 

I noticed that this only happens when the switch to inform subscribers is activated.

**Comment by matusfaro** [comment]
@julianebert That's strange, I wasn't able to reproduce your issue. The next time it happens, could you look at the console logs and paste here? RIght click -> Inspect -> Console

**Comment by julianebert** [comment]
I was not able to reproduce this again.
