### ISSUE TITLE
Discussing architecture

### ISSUE THREAD

**Issue by arthurlauck** [clearflask/clearflask#120]
Hello, discovered clear flask in this discussing in reddit: https://www.reddit.com/r/aws/comments/yh6bzf/aws_solution_to_unlimited_custom_domain_for/

I'm interested to know, how your implementation of having custom domain for customer is working.

Can you contact me in my email? arthurnascimentolauck@gmail.com

Thank you!

**Comment by matusfaro** [comment]
Yes of course, what would you like to know?

**Comment by arthurlauck** [comment]
So, I'm working in a project that is a ecommerce plataform that needs basically the same solution, custom domains for the customers.

I was looking at some solutions, like splitting into multiple cloud fronts, cloudflare for saas and others.

How your solution is working?

You customer points their CNAME in your dns, that is pointed to a public ELB (working as NLB), pointed to a caddy target/scalling group? That handles the SSL/TLS? Where are you storing the certificates to be safe? The caddy servers are pointing to another ELB (ALB), routing to the app?

How is the costs for your solution, is it ok? For what I see, NLB is expensive.

The cons of losing the CDN benefit, close to client, low latency, easy chacing policies, waf and stuff, is it worth it? Didn't you get affected too much by this?

Thank you!

**Comment by matusfaro** [comment]
> You customer points their CNAME in your dns, that is pointed to a public ELB (working as NLB), pointed to a caddy target/scalling group?

Yes, first request goes to `<customer>.clearflask.com`, hits the NLB, hits the backend server with server-side rendering. All other resources are then pulled in via `clearflask.com` which goes to CloudFront to S3.

CloudFront has its own TLS cert. My server handles cert management: fetching, renewing, storing. I used a NodeJS library ACME/Greenlock which is a terrible library you should never use. I ended up reimplenting the same logic in Java. Calls out to Let's Encrypt, calls out to Route53, stores certs in DynamoDB. It's all open-source in this repo, but not easily consumable in another project.

> Where are you storing the certificates to be safe?

In DynamoDB, not necessarily a safe place.

> How is the costs for your solution, is it ok? For what I see, NLB is expensive.

The same load balancer I have behind CloudFront is used for the subdomain. It is not necessary for this setup, I have it for auto-scaling. You can have a single server only.

> The cons of losing the CDN benefit

This is only for the initial request which I so server-side rendering for anyway so there is no benefit even if it was behind a CDN.

I am also not at a scale that it matters and considering you see NLB as an expensive service, I am inclined to guess you are neither. I suggest you do the easiest thing that works now and spend improving it later on if you need to.

--

Let me know if you have any more questions!
