### ISSUE TITLE
User not persisted after restart

### ISSUE THREAD

**Issue by abdalem** [clearflask/clearflask#124]
It's something really weird, but user is actually not persisted after restarting the docker containers. Default stack with localstack and all volumes are persisted on the host, same way as the docker-compose.yml of the repo. Is there anything to set in config ?

**Comment by matusfaro** [comment]
@abdalem Ah Localstack recently made persistence a Pro feature and it stopped working. I updated the `docker-compose.yml` file which you can [get here that will work again](https://github.com/clearflask/clearflask/blob/master/clearflask-release/src/main/docker/compose/docker-compose.self-host.yml). I pinned the last working version. Afterwards, your data will live in the `data` folder from where you ran your docker compose.

**Comment by haogeek** [comment]
FYI, I found a thirdparty docker image based on localstack 3 and supports persistence: https://hub.docker.com/r/gresau/localstack-persist . Tested and it works.
