### ISSUE TITLE
Crash when customising the public feedback filtering by category:task and status:ideas

### ISSUE THREAD

**Issue by 1tomaszwrobel** [clearflask/clearflask#128]
**Description**
When customising the public feedback filtering by `category:task` and `status:ideas`, the app crashes.

**To Reproduce**
1. Go to Settings > Advanced > Layout > Feedback > Explorer
2. Set default filtering: `category:task` and `status:ideas`
3. Save changes
4. Go to public view of feedback/feature requests

**Expected behaviour**
The public feedback list has default filters on.

**Screenshots**
![image](https://github.com/clearflask/clearflask/assets/95363812/cfe144cf-16f2-4149-bd94-7bd8e0dd1327)
![image](https://github.com/clearflask/clearflask/assets/95363812/25ddf92b-7a4e-46e9-a183-6fb21d51b775)

**Comment by matusfaro** [comment]
In this particular case, you need to allow users to create those categories under Settings > Advanced > Content > Task&Idea > "User creatable" set as "Enabled".

Unfortunately the Advanced settings have many ways that can be misconfigured.
