### ISSUE TITLE
Can I update translation directly with self-host docker instance?

### ISSUE THREAD

**Issue by haogeek** [clearflask/clearflask#136]
I just want to know if I can use docker volume to easily update any file of the docker instance then update the translation on the fly (withour any build/rebuild), or maybe the only way is to submit a new PR?

I'd like to contribute for the Chinese Simplified translation. I found the currrent translation is not complete and some words are not accurate.

**Comment by matusfaro** [comment]
Hi @haogeek, unfortunately you can't easily change them, you can either:

1. Make the translation suggestions using Crowdin which I'll pull in and build a new Docker container: https://crowdin.com/project/clearflask - highly appreciated
2. Manually edit them and re-build ClearFlask - not recommended

**Comment by matusfaro** [comment]
@haogeek Let me know if Crowdin is not accessible to you, in that case I would also accept a PR as well that directly changes the [translation files](https://github.com/clearflask/clearflask/tree/master/clearflask-i18n/src/main/resources/i18n/zh) in this repo, and I'll sync it to Crowdin as well.

**Comment by haogeek** [comment]
@matusfaro Yes I can access Crowdin, I‘ll help updating the translation on my spare time. By the way, what I said about "incomplete translation" is that a lot of UI label and text are not translatable, I didn't find the corresponding strings in Crowdin, are you willing to make the whole UI translatable?

![image](https://github.com/clearflask/clearflask/assets/4096257/c8489ec9-3488-4398-ab11-a34cbc057727)

**Comment by matusfaro** [comment]
I added a few more string to be translatable, but there are a lot more. I will post back here once I add them all in.

**Comment by matusfaro** [comment]
@haogeek I setup all remaining strings that I could find in the App platform (not the Dashboard or landing page) and did AI translation for Chinese to get a basic translation. Feel free to contribute at any time either through Crowdin or via PR.

If you find any more strings that are not able to be translated, let me know here and I will add them.
