### ISSUE TITLE
Unable to upload images correctly in the feedback

### ISSUE THREAD

**Issue by CreepyJ** [clearflask/clearflask#146]
I am trying to upload images in a feedback, but it would be like this:
![image](https://github.com/clearflask/clearflask/assets/39795353/36934e67-a368-44f4-9799-e163756028d1)
I found that the image has been successfully uploaded, but when retrieving the image, the URL does not have a port number.
![屏幕截图 2024-03-06 121554](https://github.com/clearflask/clearflask/assets/39795353/3c716643-d9bd-4353-a3e3-91955ff9d064)
So I add the a port number to this property.
![屏幕截图 2024-03-06 121658](https://github.com/clearflask/clearflask/assets/39795353/06d080a8-335d-4f91-bdb4-01298c2b8a5c)
Now I can see the image on the preview.
![屏幕截图 2024-03-06 122111](https://github.com/clearflask/clearflask/assets/39795353/21025784-25e4-4108-812c-f63d5afd12c0)
But after submitting, the image is missing.
![屏幕截图 2024-03-06 122228](https://github.com/clearflask/clearflask/assets/39795353/94858416-2ee7-46f7-b39d-d71fdad22147)

I use ClearFlask on:
- [√] Self-hosted (Own domain)
- [ ] Cloud (clearflask.com)
- [ ] Haven't tried (yet)

My financial contributions to ClearFlask:
- [√] I use a free Plan
- [ ] Thinking about it
- [ ] Monthly / Yearly Plan
- [ ] Lifetime Plan

This is high priority request:
- [ ] Yes

**Comment by matusfaro** [comment]
Unfortunately I don't support accessing ClearFlask by IP. There are probably more issues you will run into, please setup a hostname or a domain name for your installation and add an SSL/TLS certificate.
