### ISSUE TITLE
element-attribute violations(s): {img =[]}

### ISSUE THREAD

**Issue by T0LED0** [clearflask/clearflask#149]
We are carrying out the assessment through a self-managed installation.

We are experiencing an issue uploading some media and it is not saved. It appears in the edit but as soon as we click save it disappears.

We use AWS S3 instead of localstack (*same with localstack and got the same error).

I was able to verify that the file is sent to the aws s3 bucket... so we load the log from the server name container, and I see the following error:

14:23:35.222 [http-nio-8080-exec-6] INFO c.s.c.web.security.Sanitizer - HTML policy violation(s) for devops-zzzr7 idea id test-790, element attribute violations: {img =[]}

---

I use ClearFlask on:

- [X] Self-hosted (Own domain)
- [ ] Cloud (clearflask.com)
- [ ] Haven't tried (yet)

My financial contributions to ClearFlask:

- [X] I use a free Plan
- [ ] Thinking about it
- [ ] Monthly / Yearly Plan
- [ ] Lifetime Plan

I'd be willing to implement this feature:

- [ ] Yes

**Comment by matusfaro** [comment]
Stepping through the code, some of the reasons this could be failing is:

- Misconfigured property `com.smotana.clearflask.store.impl.S3ContentStore$Config.hostname=`. For real S3, it should be something like `<bucket_name>.s3.amazonaws.com`
- `com.smotana.clearflask.store.impl.S3ContentStore$Config.scheme=` should be `https` or commented out for real S3
- Should not be using any of these properties: `serviceEndpoint`, `signingRegion`, `proxyEnabled` and `proxyResolveTo` with the prefix `com.smotana.clearflask.store.s3.DefaultS3ClientProvider$Config.`

You may also post your config file and I can see if there is anything that stands out.

**Comment by T0LED0** [comment]
follow the configuration block

![image](https://github.com/clearflask/clearflask/assets/22472103/72717969-b513-4260-9a8f-c4f82db3da9f)

**Comment by T0LED0** [comment]
Thanks for the help.

This configuration worked for me now.

I changed the s3 path as per your example.

![image](https://github.com/clearflask/clearflask/assets/22472103/5c801001-f742-4ee9-a04a-245c83f48078)

**Comment by matusfaro** [comment]
Awesome! I made a note in the configuration for future.
