### ISSUE TITLE
[Feature Request] Custom Analytics Option

### ISSUE THREAD

**Issue by ZandercraftGames** [clearflask/clearflask#58]
The addition of a custom analytics option would help significantly as it would allow people who opt to use their own analytics solution to add their own tracking codes.
This would be an integration that would allow the insertion of HTML code at the end of the body tag on all pages.

**Comment by matusfaro** [comment]
This is already possible although not very well documented.

Go to `<YOUR_DOMAIN>/dashboard/settings/project/advanced/style` -> `Custom Templates` -> `Footer`

This input box is treated as a [Liquid](https://shopify.github.io/liquid/) template that will be pasted as raw HTML at the bottom of the page so you can add your own script tags here.

HOWEVER: I just found out that pasting script tags is not escaped properly. I am rolling out a new version `1.5.7` within a few hours that you can deploy to fix this. Wait to upgrade before you try it out yourself.
