### ISSUE TITLE
Reloading Page Causes Redirect

### ISSUE THREAD

**Issue by ZandercraftGames** [clearflask/clearflask#59]
Reloading the page causes the user to be redirected to <yourdomain.com>/dashboard, regardless of if the user is logged in or not.
This is extremely inconvenient as users are sent to a page they have no access to and are denied access just for reloading the page.

This also happens whenever the user directly visits a link instead of clicking the button to go to that page, which I suspect is the actual problem here. This also means that authentication using oauth redirects to the dashboard URL, presenting the user with the "Welcome back to ClearFlask" login page.

**Comment by ZandercraftGames** [comment]
> Interesting, is it publicly accessible where I can see this?
> 
> Also please review the setup section and make sure the configuration is setup correctly for your setup including domain name and certificate management options:
> https://github.com/clearflask/clearflask#dns
> 
> If it's still not working, please post your configuration and I'll try to reproduce it.

You can view the instance at https://help.zandercraft.ca.

I will post my configurations shortly.

**Comment by matusfaro** [comment]
I found the issue, I will let you know once a fix is out...

**Comment by ZandercraftGames** [comment]
> I found the issue, I will let you know once a fix is out...

Thanks! I really appreciate everything. This is honestly a great piece of software! You've done a great job with it!

**Comment by matusfaro** [comment]
Fix is in `1.5.8`, try it out. There is a chance that my fix didn't fix your particular issue, so please reopen the issue if it doesn't work.

--

> Thanks! I really appreciate everything. This is honestly a great piece of software! You've done a great job with it!

Thank you for the compliment, I appreciate it.

**Comment by ZandercraftGames** [comment]
> Fix is in `1.5.8`, try it out. There is a chance that my fix didn't fix your particular issue, so please reopen the issue if it doesn't work.
> 
> --
> 
> > Thanks! I really appreciate everything. This is honestly a great piece of software! You've done a great job with it!
> 
> Thank you for the compliment, I appreciate it.

As far as I can tell, the issue has been resolved.
