### ISSUE TITLE
Admin Users

### ISSUE THREAD

**Issue by GodOfWonders** [clearflask/clearflask#83]
So I love this so far but the only thing I'm struggling with, and I don't know if I missed documentation somewhere, is I see there is an ability to invite users in the project panel.  I know this doesn't work because of the superadmin regex and the setting the user registration to false. 
One thing that really drew me to this is so the team I collaborate with can move away from Trello.  Trello has a nice roadmap board but allowing users to submit ideas and vote on them is less than ideal.  This looks like the nice bridge between the gap for that.  However, I only see the ability to toggle users as Mods, which is great to have people moderating the comments, or posting suggestions for someone, but I see no where to assign Admin users.
Since I collab with others that release things as well, sometimes independently, I'd need for them to be able to adjust the roadmap as well.  Currently I only see a way for me to adjust it solo on a self-hosted docker instance and no one else.
Is there something I'm missing in the documentation somewhere or is this not currently possible?

**Comment by matusfaro** [comment]
I see your use case, as it is right now I haven't taken it into consideration. Also I realized that it's a little bit confusing what the different roles are capable of doing.

Currently we have user, moderator, admin, and super admin. From your use case of wanting every member to be able to us the Dashboard, I would suggest to have everyone as an admin (Or super admin if you want to allow them creating new projects, etc..). That should mostly solve your problem. Not sure if you stumbled upon this page, but [here you can add new admins](https://clearflask.com/dashboard/settings/project/teammates) (confusingly called teammates):

<img width="749" alt="image" src="https://user-images.githubusercontent.com/4206738/177233363-374aaa5d-9a12-444e-8e8a-dbcc1ddbf03a.png">

**For self-hosted,** just enable registration via configuration. If you want everyone to be superadmin, you can make the superadmin a catch-all `.*` regex. In this case, you should not expose your instance to untrusted parties as they will be able to register and become superadmin.

**For cloud service,** you can simply start adding new admins to your project. Keep in mind the Standard plan charges per admin which can be pricey. If you reach out to me by email, I can setup a flat plan for you so you pay one price for unlimited admin teammates.

Caveat:
- Modifications in the dashboard do not support collaboration well. What I mean is that if one user makes a change, this change is not immediately propagated to other users' open dashboard page. They would have to reload the page to see the effect.

Please do let me know specific changes you would like to see to make your use case better for team collaboration. Anything that comes to mind, please share it with me. I will try my best to get those features in. Also if you are planning to become a paid cloud customer, I will also make those features the top of my list.

**Comment by GodOfWonders** [comment]
Thank you for the response.  We are a small team that build out extended features for a software becoming more widely popular with streamers on Twitch with it's debut on YouTube on the latest version.  So while real time reflection across panels would be a super nice addition I'm not expecting it to be a necessity at this moment.  I currently self host most of the stuff I utilize for this project and was looking at something that would allow my small team to get ideas of things to build from the community and then display the status in a public roadmap function.

While I've seen some things that have already been suggested, like assigning the Discord avatar as the user avatar, it's still pretty close to what I'm looking for.  Mainly there's only little QoL things I'd love to be able to do like changing the navbar, instead of feedback I'm calling it ideas and announcements are releases but nothing majorly breaking and mainly just little QoL things.

I did try assigning teammates as I thought that was how I should be able to assign Admins in the self-hosted docker container, I don't need everyone to have access to superadmin mainly so no one can nuke anything of high importance so was just trying to go with assigning Admin.  After allowing registrations in the config it would return an error for them even using the invitation link saying that admin@localhost was the only one allowed to register.  Even though I had changed the regex superadmin to my email address (as I was just trying to assign them Admin).  After looking through the documentation and closed issues I couldn't find an answer to getting the Admin assignment to work on the self-hosted docker so that's why I ended up asking here.  Hoping maybe some light could be shed on what I'm doing wrong (I'll admit...it's usually something I did wrong >_<).

**Comment by matusfaro** [comment]
> changing the navbar

Although the portal is fully customizable, the Dashboard navbar is not. This would be a bit of over-customization in my opinion. But you are free to fork and change it for your own instance :)

>  After allowing registrations in the config it would return an error

Ah yes, I went through the code and there is an explicit check to only allow superadmins to sign up for self-hosted instances. Considering there is a config toggle to disable signups, I removed this restriction.

You can either make everyone a super admin to allow them to signup or wait for the new patch release version `1.5.11` that will include the fix for non-super admins to signup (Should be out within a day).

**Comment by GodOfWonders** [comment]
I appreciate it.  I can wait for the update.  No worries.  Just wanted to make sure I wasn't doing something wrong.  I'll be happy just being able to add or remove admins.  The other stuff is, like I said, more of a QoL thing.

> Although the portal is fully customizable, the Dashboard navbar is not. This would be a bit of over-customization in my opinion. But you are free to fork and change it for your own instance :)

Just to clarify I wasn't speaking about the Dashboard navbar unless what you and I are referencing are the same thing.  I was more speaking about how my landing page reads this:
![image](https://user-images.githubusercontent.com/33267417/177433843-1bc2083d-0d2c-4e05-aa29-7daa3af271cc.png)
but my navbar here reads this:
![image](https://user-images.githubusercontent.com/33267417/177433879-e8415514-98b5-4a99-bd98-7b309918039b.png)
after seeing how the locale stuff is tied to translating that, an option to hide it wouldn't be a bad idea but more of a people are gonna say stuff to me about it but not anything breaking.

The only other thing I did see that I would love to be able to do is change or remove the heading in Announcements much like can be done in Feedback, Roadmap, or the Landing Page so I can either change or remove this:
![image](https://user-images.githubusercontent.com/33267417/177434369-652f5bda-ea10-46c3-8c73-47556ca8231d.png)

After I use it for a bit I can give more feedback once I get some from our users that use it if you'd like.  You've made a nice piece of software here that I think can be stretched out to many different use cases.  I just appreciate you taking your time to respond and willingness to help me out with the issue.  I really wasn't expecting a quick/or even a response to my issue let alone asking for feedback and pushing a fix for my issue soon.  So just know I am super grateful and look forward to using this with our community.

**Comment by matusfaro** [comment]
>  I can wait for the update

I am building it now, expect it within an hour

> I wasn't speaking about the Dashboard navbar

Got it. You're in luck, almost everything is customizable in the portal and if it isn't, I can make it customizable.

> but my navbar here reads this

If you go into the advanced settings, `https://<your-domain>/dashboard/settings/project/advanced/layout`, there you can modify the text for each navbar item. I suggest you modify the name of the page, and the navbar title reflects the same name like this:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/4206738/177462464-8f7c2822-8680-4816-88c9-c37f61b99539.png">

If you want to have a different name for the page and the navbar, you can instead override the navbar text on the same page if you scroll down here:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/4206738/177462397-1415c42f-b2d2-4b48-a516-ecfe53299112.png">

> change or remove the heading in Announcements

Under the same settings link, Advanced -> Layout, open the announcements page (Click the three dots or in the side menu click the annoucnements page). Then you can modify the text "Changes we made" under "Heading" and "Description" property.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/4206738/177462285-db2af112-3771-4960-9401-65dd0d840eb1.png">

After you modify it, be sure to preview it before publishing:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/4206738/177462319-a6772a10-e7c7-4e02-b4cb-e6f1122b328d.png">
