### ISSUE TITLE
Description is not saving on local docker instalation

### ISSUE THREAD

**Issue by yalagin** [clearflask/clearflask#93]
Hi thanks for making Clearflask opensource.
There is an issue form clean install on docker-compose
when user goes to the /feedback and leaves the feedback description is ignored 
also is there are some permissions for normal user to link ideas together? I got an error with "Not allowed to merge". If so I could not find it in /dashboard
thanks

**Comment by matusfaro** [comment]
Thanks for the bu report,there are two issues here:

> when user goes to the /feedback and leaves the feedback description is ignored

This is a bug report I received before but can never track down, can you give more information on how you got this bug? Which browser do you use? Maybe some screenshots? It would be very much appreciated.

> I got an error with "Not allowed to merge"

I fixed the issue, it will be released in the next few days with a minor release.

**Comment by matusfaro** [comment]
Oops didn't mean to close this. Please do give me more info on the first issue
